### ISSUE TITLE
syntax error, unexpected '&' in announce.php on line 65

### ISSUE THREAD

**Issue by l2dy** [nwafu-mta/mtpt#5]
```
$ php -v
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
$ php -l announce.php

Parse error: syntax error, unexpected '&' in announce.php on line 65
Errors parsing announce.php
```

**Comment by bianyifan** [comment]
php 7 is not supported, please use php 5.3



发自我的小米手机
在 Zero King <notifications@github.com>，2018年4月30日 16:18写道：

$ php -v
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
$ php -l announce.php

Parse error: syntax error, unexpected '&' in announce.php on line 65
Errors parsing announce.php

**Comment by l2dy** [comment]
Please add supported PHP versions to README or INSTALL.

PHP 5.3 is unsupported [since 14 Aug 2014](https://secure.php.net/eol.php) and PHP 5.6 will receive security support [until 31 Dec 2018](https://secure.php.net/supported-versions.php). If possible, please port MTPT to PHP 7.

**Comment by bianyifan** [comment]
README.md has been updated.

We are not going to port MTPT to PHP 7 because its code is full of mess. We may start a new private tracker project.
